# Generated by Django 5.2.13 on 2026-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='brightness',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='image',
            name='contrast',
            field=models.FloatField(default=1.0),
        ),
    ]
